

services:
  postgres:
    #image: postgres-demo:latest
    image: public.ecr.aws/i0v0m7z7/class06/postgresql-demo:latest
    volumes:
    - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: 123456
    ports:
    - "5432:5432"
  keycloak:
    #image: keycloak-demo:latest
    image: public.ecr.aws/i0v0m7z7/class06/kc-demo:latest
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: 123456
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
    #- "8080:8080"
    - "8443:8443"
    depends_on:
    - postgres

volumes:
      postgres_data:
        driver: local